.TH FM 1 "fm 1.0.2"
.SH NAME
fm \- control frequency, volume, mute/unmute of FM radio card
.SH SYNOPSIS
.HP
.B fm
[
.B \-h
] [
.B \-o
] [
.B \-q
] [
.B \-d
.I device
] [
.B \-t
.I tuner
] [
.B \-T
.B none
|
.B forever
|
.I time
]
.B on
|
.B off
|
.B +
|
.B \-
|
.B freq
[
.I volume
]
.SH DESCRIPTION
.B fm
is a program to control the frequency, volume, and mute/unmute state
of an FM radio card, using the video4linux interface introduced in
2.1.x series Linux kernels.
.SS OPTIONS
.PP
.TP
.B \-h
Print a usage message to standard output, and exit.
.TP
.B \-o
Ignore frequency range limits of card.  Use if you suspect that the
card supports a wider frequency range than its driver believes.
.TP
.B \-q
Quiet mode.  Keeps information on station and volume from being
printed on standard output.
.TP
\fB\-d \fIdevice
Sets \fIdevice\fR as the device to tune.  The default is
\fB/dev/radio0\fR.
.TP
\fB\-t \fItuner
Sets \fItuner\fR as the tuner on the selected device to adjust.  The
default is tuner 0.  Most radio devices have only a single tuner.
.TP
\fB\-T none \fR| \fBforever \fR| \fItime
After tuning, sleep for the time specified or forever.  Time is
specified in seconds by default.  A suffix of
.B m
indicates minutes,
.B h
indicates hours, or
.D d
indicates days.
.IP
The
.B -T
option is useful with radio card drivers that only maintain the tuner
settings while the tuner's file descriptor remains open.  Try using
this option if running
.B fm
ordinarily produces only a single "pop" from your speakers.
.TP
.BI freq
Frequency to tune the radio to, in MHz.  For instance, \fB88.9\fR
specifies a frequency of 88.9 MHz.  AM tuner values are also specified
in MHz; for instance, 530 kHz would be specified as \fB.530\fR.
.TP
.BI on
Turn the radio on (unmute).
.TP
.BI off
Turn the radio off (mute).
.TP
.BI volume
Specify the desired volume, in percent.  Not all radio devices support
volume control.
.TP
.BI +
Increase the current volume.
.TP
.BI -
Decrease the current volume.
.SH CONFIGURATION
.B fm
reads \fI$HOME\fB/.fmrc\fR, if it exists, to obtain default settings.
Each line may take one of the following forms:
.TP
.BR VOL \ percent
Specifies default volume (default: 12.5%).
.TP
.BR INCR \ percent
Volume increment used for
.B +
and
.B -
options (default: 10%).
.TP
.BR TIME
Default sleep time (default:
.BR none ).
.PP
All other lines are ignored.
.SH SEE ALSO
.TP
Additional documentation:
.B /usr/share/doc/fmtools/README
.TP
The fmtools homepage:
.B http://benpfaff.org/fmtools
.TP
The video4linux webpage:
.B http://www.exploits.org/v4l/
.SH AUTHORS
Russell Kroll <rkroll@exploits.org>, now maintained by Ben Pfaff
<blp@cs.stanford.edu>.  Sleep time feature contributed by Dave Ulrick
<d-ulrick@insightbb.com>.  This manpage written by Ben Pfaff.
