.TH FM 1 "fmscan 1.0.2"
.SH NAME
fmscan \- scan FM band for radio stations
.SH SYNOPSIS
.HP
.B fm
[
.B \-h
] [
.B \-d
.I device
] [
.B \-s
.I freq
] [
.B \-e
.I freq
] [
.I \-i
.I freq
]
.SH DESCRIPTION
.B fmscan
is a program to scan a frequency band for radio stations, using the
video4linux interface introduced in 2.1.x series Linux kernels.  It
shows which ones have a accumulated signal strength of 50% or higher.
.SS OPTIONS
.PP
.TP
.B \-h
Print a usage message to standard output, and exit.
.TP
\fB\-d \fIdevice
Sets \fIdevice\fR as the device to tune.  The default is
\fB/dev/radio0\fR.
.TP
\fB\-s \fIfreq
Starting frequency for scan, in MHz.  Default: 87.9.
.TP
\fB\-e \fIfreq
Ending frequency for scan, in MHz.  Default: 107.9.
.TP
\fB\-i \fIfreq
Increment between scanned channels, in MHz.  Default: 0.2.
.TP
\fB\-t \fIpercent
Signal strength threshold to consider a channel.  Default: 50%.
.SH BUGS
This process can take a while, and results vary greatly depending on the
radio card in use.  If your card's hardware cannot report signal
strength, it will not produce useful results.
.PP
This program may not do much if your radio card's driver doesn't support
fine tuning in 1/16000 MHz offsets.  By default, v4l assumes 1/16 MHz
tuning units, which introduces evil rounding errors on many frequencies.
If in doubt, grep for VIDEO_TUNER_LOW in your driver's source.
.PP
Supports only tuner 0 on any given device.
.SH SEE ALSO
.TP
Additional documentation:
.B /usr/doc/fmtools/README
.TP
The fmtools homepage:
.B http://www.exploits.org/v4l/fmtools.html
.TP
The video4linux webpage:
.B http://roadrunner.swansea.uk.linux.org/v4l.shtml
.SH AUTHORS
Russell Kroll <rkroll@exploits.org>, now maintained by Ben Pfaff
<blp@cs.stanford.edu.>. This manpage written by Ben Pfaff.
